project:
  type: website

website:
  title: "Patrick Deutschmann"
  navbar:
    right:
      - about.qmd
      - text: CV
        href: resume.pdf
      - icon: github
        href: https://github.com/deutschmn
      - icon: mastodon
        href: https://hachyderm.io/@pdeutschmn
      - icon: linkedin
        href: https://www.linkedin.com/in/patrick-deutschmann/
format:
  html:
    # theme: cosmo
    theme: flatly
    # theme: sandstone
    # theme: simplex
    # theme: litera
    # theme: lux
    css: styles.css
execute:
  freeze: auto
