project:
  type: website

website:
  title: "Patrick Deutschmann"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/deutschmn
      - icon: mastodon
        href: https://hachyderm.io/@pdeutschmn
      - icon: linkedin
        href: https://www.linkedin.com/in/patrick-deutschmann/
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto
